spring:
  application:
    name: TCGArkhive

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver


tcgarkhive:
  auth:
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    access-token-secret: ${ACCESS_TOKEN_SECRET}

    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
    refresh-token-secret: ${REFRESH_TOKEN_SECRET}

    pwd-reset-secret: ${PASSWORD_RESET_SECRET}
    pwd-reset-token-expiration: ${PASSWORD_RESET_TOKEN_EXPIRATION}
    pwd-reset-endpoint: http://localhost:8080/api/v1/user/password/reset?token=

logging:
  level:
    org:
      springframework:
          security:
            messaging: debug
          web:
            socket: debug
          messaging: debug